export const AIRPORTS = [
    { code: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "USA" },
    { code: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
    { code: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
    { code: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
    { code: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan" },
    { code: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
    { code: "LHR", name: "Heathrow Airport", city: "London", country: "UK" },
    { code: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
    { code: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
    { code: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "USA" },
    { code: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands" },
    { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
    { code: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
    { code: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
    { code: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
    { code: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore" },
    { code: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
    { code: "DEN", name: "Denver International Airport", city: "Denver", country: "USA" },
    { code: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
    { code: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
    { code: "BCN", name: "Josep Tarradellas Barcelona-El Prat Airport", city: "Barcelona", country: "Spain" },
    { code: "MAD", name: "Adolfo Suárez Madrid-Barajas Airport", city: "Madrid", country: "Spain" },
    { code: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
    { code: "FCO", name: "Leonardo da Vinci-Fiumicino Airport", city: "Rome", country: "Italy" },
    { code: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
    { code: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
    { code: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
    { code: "GRU", name: "São Paulo/Guarulhos–Governador André Franco Montoro International Airport", city: "São Paulo", country: "Brazil" },
    { code: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "Mexico" },
    { code: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
    { code: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "USA" },
    { code: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "USA" },
    { code: "EWR", name: "Newark Liberty International Airport", city: "Newark", country: "USA" },
    { code: "MCO", name: "Orlando International Airport", city: "Orlando", country: "USA" },
    { code: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", country: "USA" },
    { code: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "USA" },
    { code: "IAH", name: "George Bush Intercontinental Airport", city: "Houston", country: "USA" },
    { code: "BOS", name: "Logan International Airport", city: "Boston", country: "USA" },
    { code: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "USA" },
    { code: "DTW", name: "Detroit Metropolitan Wayne County Airport", city: "Detroit", country: "USA" },
    { code: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "USA" },
    { code: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "USA" },
    { code: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
    { code: "BWI", name: "Baltimore/Washington International Thurgood Marshall Airport", city: "Baltimore", country: "USA" },
    { code: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", country: "USA" },
    { code: "SAN", name: "San Diego International Airport", city: "San Diego", country: "USA" },
    { code: "IAD", name: "Washington Dulles International Airport", city: "Washington D.C.", country: "USA" },
    { code: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington D.C.", country: "USA" },
    { code: "TPA", name: "Tampa International Airport", city: "Tampa", country: "USA" },
    { code: "PDX", name: "Portland International Airport", city: "Portland", country: "USA" },
    { code: "HNL", name: "Daniel K. Inouye International Airport", city: "Honolulu", country: "USA" },
    { code: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
    { code: "YUL", name: "Montréal-Pierre Elliott Trudeau International Airport", city: "Montreal", country: "Canada" },
    { code: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
    { code: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
    { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
    { code: "OSL", name: "Oslo Airport", city: "Oslo", country: "Norway" },
    { code: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
    { code: "HEL", name: "Helsinki Airport", city: "Helsinki", country: "Finland" },
    { code: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
    { code: "LIS", name: "Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
    { code: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
    { code: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy" },
    { code: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
    { code: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
    { code: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
    { code: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary" },
    { code: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
    { code: "SAW", name: "Sabiha Gökçen International Airport", city: "Istanbul", country: "Turkey" },
    { code: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia" },
    { code: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia" },
    { code: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
    { code: "AUH", name: "Zayed International Airport", city: "Abu Dhabi", country: "UAE" },
    { code: "TLV", name: "Ben Gurion Airport", city: "Tel Aviv", country: "Israel" },
    { code: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
    { code: "JNB", name: "O. R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
    { code: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa" },
    { code: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria" },
    { code: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
    { code: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
    { code: "DEL", name: "Indira Gandhi International Airport", city: "Delhi", country: "India" },
    { code: "BLR", name: "Kempegowda International Airport", city: "Bangalore", country: "India" },
    { code: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India" },
    { code: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", country: "India" },
    { code: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India" },
    { code: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
    { code: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia" },
    { code: "DPS", name: "I Gusti Ngurah Rai International Airport", city: "Denpasar", country: "Indonesia" },
    { code: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
    { code: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam" },
    { code: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam" },
    { code: "TPE", name: "Taoyuan International Airport", city: "Taipei", country: "Taiwan" },
    { code: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "China" },
    { code: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
    { code: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
    { code: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
    { code: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
    { code: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
    { code: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
    { code: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina" },
    { code: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile" },
    { code: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia" },
    { code: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru" },
    { code: "PTY", name: "Tocumen International Airport", city: "Panama City", country: "Panama" },
    // Vietnam
    { code: "DAD", name: "Da Nang International Airport", city: "Da Nang", country: "Vietnam" },
    { code: "HUI", name: "Phu Bai International Airport", city: "Hue", country: "Vietnam" },
    { code: "CXR", name: "Cam Ranh International Airport", city: "Nha Trang", country: "Vietnam" },
    { code: "PQC", name: "Phu Quoc International Airport", city: "Phu Quoc", country: "Vietnam" },
    { code: "DLI", name: "Lien Khuong Airport", city: "Da Lat", country: "Vietnam" },
    { code: "VCA", name: "Can Tho International Airport", city: "Can Tho", country: "Vietnam" },
    { code: "VII", name: "Vinh International Airport", city: "Vinh", country: "Vietnam" },
    // Thailand
    { code: "HKT", name: "Phuket International Airport", city: "Phuket", country: "Thailand" },
    { code: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai", country: "Thailand" },
    { code: "CEI", name: "Chiang Rai International Airport", city: "Chiang Rai", country: "Thailand" },
    { code: "KBV", name: "Krabi International Airport", city: "Krabi", country: "Thailand" },
    { code: "USM", name: "Samui Airport", city: "Koh Samui", country: "Thailand" },
    { code: "HHQ", name: "Hua Hin Airport", city: "Hua Hin", country: "Thailand" },
    // Indonesia / Malaysia / Philippines / Singapore region
    { code: "JOG", name: "Yogyakarta International Airport", city: "Yogyakarta", country: "Indonesia" },
    { code: "LOP", name: "Lombok International Airport", city: "Lombok", country: "Indonesia" },
    { code: "LGK", name: "Langkawi International Airport", city: "Langkawi", country: "Malaysia" },
    { code: "PEN", name: "Penang International Airport", city: "Penang", country: "Malaysia" },
    { code: "BKI", name: "Kota Kinabalu International Airport", city: "Kota Kinabalu", country: "Malaysia" },
    { code: "CEB", name: "Mactan-Cebu International Airport", city: "Cebu", country: "Philippines" },
    { code: "MPH", name: "Godofredo P. Ramos Airport", city: "Boracay", country: "Philippines" },
    { code: "PPS", name: "Puerto Princesa International Airport", city: "Palawan", country: "Philippines" },
    // Cambodia / Laos / Myanmar
    { code: "REP", name: "Siem Reap International Airport", city: "Siem Reap", country: "Cambodia" },
    { code: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", country: "Cambodia" },
    { code: "VTE", name: "Wattay International Airport", city: "Vientiane", country: "Laos" },
    { code: "LPQ", name: "Luang Prabang International Airport", city: "Luang Prabang", country: "Laos" },
    { code: "RGN", name: "Yangon International Airport", city: "Yangon", country: "Myanmar" },
    // East Asia — additions
    { code: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan" },
    { code: "OKA", name: "Naha Airport", city: "Okinawa", country: "Japan" },
    { code: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan" },
    { code: "NGO", name: "Chubu Centrair International Airport", city: "Nagoya", country: "Japan" },
    { code: "HIJ", name: "Hiroshima Airport", city: "Hiroshima", country: "Japan" },
    { code: "PUS", name: "Gimhae International Airport", city: "Busan", country: "South Korea" },
    { code: "CJU", name: "Jeju International Airport", city: "Jeju", country: "South Korea" },
    { code: "KHH", name: "Kaohsiung International Airport", city: "Kaohsiung", country: "Taiwan" },
    { code: "MFM", name: "Macau International Airport", city: "Macau", country: "China" },
    { code: "SZX", name: "Shenzhen Bao'an International Airport", city: "Shenzhen", country: "China" },
    { code: "CTU", name: "Chengdu Shuangliu International Airport", city: "Chengdu", country: "China" },
    { code: "XIY", name: "Xi'an Xianyang International Airport", city: "Xi'an", country: "China" },
    // South Asia
    { code: "GOI", name: "Goa International Airport", city: "Goa", country: "India" },
    { code: "COK", name: "Cochin International Airport", city: "Kochi", country: "India" },
    { code: "JAI", name: "Jaipur International Airport", city: "Jaipur", country: "India" },
    { code: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka" },
    { code: "MLE", name: "Velana International Airport", city: "Malé", country: "Maldives" },
    { code: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal" },
    { code: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh" },
    // Middle East additions
    { code: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman" },
    { code: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait" },
    { code: "BAH", name: "Bahrain International Airport", city: "Manama", country: "Bahrain" },
    { code: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "Jordan" },
    { code: "AQJ", name: "King Hussein International Airport", city: "Aqaba", country: "Jordan" },
    { code: "BEY", name: "Beirut–Rafic Hariri International Airport", city: "Beirut", country: "Lebanon" },
    // Europe — popular leisure airports
    { code: "AGP", name: "Málaga Airport", city: "Málaga", country: "Spain" },
    { code: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain" },
    { code: "ALC", name: "Alicante–Elche Airport", city: "Alicante", country: "Spain" },
    { code: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain" },
    { code: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain" },
    { code: "PMI", name: "Palma de Mallorca Airport", city: "Palma de Mallorca", country: "Spain" },
    { code: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain" },
    { code: "TFS", name: "Tenerife South Airport", city: "Tenerife", country: "Spain" },
    { code: "LPA", name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain" },
    { code: "ACE", name: "Lanzarote Airport", city: "Lanzarote", country: "Spain" },
    { code: "FUE", name: "Fuerteventura Airport", city: "Fuerteventura", country: "Spain" },
    { code: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "Portugal" },
    { code: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal" },
    { code: "FNC", name: "Madeira Airport", city: "Funchal", country: "Portugal" },
    { code: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
    { code: "LYS", name: "Lyon–Saint-Exupéry Airport", city: "Lyon", country: "France" },
    { code: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
    { code: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy" },
    { code: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy" },
    { code: "FLR", name: "Florence Airport", city: "Florence", country: "Italy" },
    { code: "CTA", name: "Catania–Fontanarossa Airport", city: "Catania", country: "Italy" },
    { code: "PMO", name: "Falcone–Borsellino Airport", city: "Palermo", country: "Italy" },
    { code: "JTR", name: "Santorini (Thira) International Airport", city: "Santorini", country: "Greece" },
    { code: "JMK", name: "Mykonos Island National Airport", city: "Mykonos", country: "Greece" },
    { code: "HER", name: "Heraklion International Airport", city: "Heraklion", country: "Greece" },
    { code: "RHO", name: "Rhodes International Airport", city: "Rhodes", country: "Greece" },
    { code: "CFU", name: "Corfu International Airport", city: "Corfu", country: "Greece" },
    { code: "SPU", name: "Split Airport", city: "Split", country: "Croatia" },
    { code: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia" },
    { code: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia" },
    { code: "TIA", name: "Tirana International Airport", city: "Tirana", country: "Albania" },
    { code: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia" },
    { code: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
    { code: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
    { code: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
    { code: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
    { code: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany" },
    { code: "KEF", name: "Keflavík International Airport", city: "Reykjavik", country: "Iceland" },
    // Americas additions
    { code: "GIG", name: "Rio de Janeiro–Galeão International Airport", city: "Rio de Janeiro", country: "Brazil" },
    { code: "BSB", name: "Brasília International Airport", city: "Brasília", country: "Brazil" },
    { code: "MVD", name: "Carrasco International Airport", city: "Montevideo", country: "Uruguay" },
    { code: "UIO", name: "Mariscal Sucre International Airport", city: "Quito", country: "Ecuador" },
    { code: "CUZ", name: "Alejandro Velasco Astete International Airport", city: "Cusco", country: "Peru" },
    { code: "CUN", name: "Cancún International Airport", city: "Cancún", country: "Mexico" },
    { code: "SJD", name: "Los Cabos International Airport", city: "Los Cabos", country: "Mexico" },
    { code: "PVR", name: "Puerto Vallarta International Airport", city: "Puerto Vallarta", country: "Mexico" },
    { code: "PUJ", name: "Punta Cana International Airport", city: "Punta Cana", country: "Dominican Republic" },
    { code: "NAS", name: "Lynden Pindling International Airport", city: "Nassau", country: "Bahamas" },
    { code: "HAV", name: "José Martí International Airport", city: "Havana", country: "Cuba" },
    { code: "SJU", name: "Luis Muñoz Marín International Airport", city: "San Juan", country: "Puerto Rico" },
    { code: "MBJ", name: "Sangster International Airport", city: "Montego Bay", country: "Jamaica" },
    // Africa additions
    { code: "RAK", name: "Marrakesh Menara Airport", city: "Marrakech", country: "Morocco" },
    { code: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco" },
    { code: "SSH", name: "Sharm El Sheikh International Airport", city: "Sharm El Sheikh", country: "Egypt" },
    { code: "HRG", name: "Hurghada International Airport", city: "Hurghada", country: "Egypt" },
    { code: "ZNZ", name: "Abeid Amani Karume International Airport", city: "Zanzibar", country: "Tanzania" },
    { code: "JRO", name: "Kilimanjaro International Airport", city: "Kilimanjaro", country: "Tanzania" },
    { code: "MRU", name: "Sir Seewoosagur Ramgoolam International Airport", city: "Port Louis", country: "Mauritius" },
    { code: "SEZ", name: "Seychelles International Airport", city: "Mahé", country: "Seychelles" },
    // Oceania additions
    { code: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia" },
    { code: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia" },
    { code: "WLG", name: "Wellington International Airport", city: "Wellington", country: "New Zealand" },
    { code: "CHC", name: "Christchurch Airport", city: "Christchurch", country: "New Zealand" },
    { code: "ZQN", name: "Queenstown Airport", city: "Queenstown", country: "New Zealand" },
    { code: "NAN", name: "Nadi International Airport", city: "Nadi", country: "Fiji" },
    { code: "PPT", name: "Faa'a International Airport", city: "Papeete", country: "French Polynesia" },
];
