/**
 * Hand-picked, Christmas-themed Unsplash photos for the festive destinations
 * in `lib/christmas.ts`, keyed by the same airport/metro code.
 *
 * Chosen once (via `images.getDestinationImages`) and baked in so the home row
 * makes zero Unsplash calls at runtime — the API isn't cached server-side and
 * the row renders 25 cards on every home-screen open. URLs hotlink the Unsplash
 * CDN (as their guidelines require) sized for a ~150pt card; credit the
 * photographer wherever one is shown.
 *
 * To swap a photo: run
 *   npx convex run --prod images:getDestinationImages "{destination: 'Vienna christmas market', count: 3}"
 * and paste the pick here with `w=500&q=70`.
 */
export type ChristmasPhoto = { url: string; photographer: string; link: string };

export const CHRISTMAS_PHOTOS: Record<string, ChristmasPhoto> = {
    VIE: { url: "https://images.unsplash.com/photo-1761273075473-889349a92fa3?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxWaWVubmElMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4MHww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Jeffrey Zhang", link: "https://unsplash.com/photos/christmas-market-carousel-with-illuminated-sign-if8oeu97KrI" },
    PRG: { url: "https://images.unsplash.com/photo-1766470656777-cff1bae082bf?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwzfHxQcmFndWUlMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4MXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Carnet de Voyage d'Alex", link: "https://unsplash.com/photos/a-large-decorated-christmas-tree-at-night-wslHiDslHKQ" },
    SXB: { url: "https://images.unsplash.com/photo-1580112613591-a4be59e156a5?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxTdHJhc2JvdXJnJTIwY2hyaXN0bWFzfGVufDB8MHx8fDE3OTA1MjA2ODB8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Alexis Brandner", link: "https://unsplash.com/photos/gold-and-white-lighted-christmas-tree-OHMRoA40xAI" },
    NUE: { url: "https://images.unsplash.com/photo-1669552698934-8c12ed9fe36b?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxOdXJlbWJlcmclMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4MXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Alexandra Zelena", link: "https://unsplash.com/photos/a-group-of-glass-ornaments-iAGKGQJGAQE" },
    BUD: { url: "https://images.unsplash.com/photo-1545903579-2577ed82e3eb?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxCdWRhcGVzdCUyMGNocmlzdG1hcyUyMG1hcmtldHxlbnwwfDB8fHwxNzkwNTIwNjgxfDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Krisztian Tabori", link: "https://unsplash.com/photos/people-gathered-outside-buildings-at-night-yzQUnbDbscI" },
    SZG: { url: "https://images.unsplash.com/photo-1742160492576-abd2940e826f?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwzfHxTYWx6YnVyZyUyMGNocmlzdG1hcyUyMG1hcmtldHxlbnwwfDB8fHwxNzkwNTIwNzgwfDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Scorn Pion", link: "https://unsplash.com/photos/christmas-market-with-people-and-festive-lights-zjn0WSjX2SM" },
    MUC: { url: "https://images.unsplash.com/photo-1734567112080-ef59a3fa9763?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxNdW5pY2glMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4Mnww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Jahanzeb Ahsan", link: "https://unsplash.com/photos/a-crowd-of-people-standing-around-a-christmas-market-ZseiLBRnP-k" },
    CGN: { url: "https://images.unsplash.com/photo-1640300323675-25e1ff4c3a11?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxDb2xvZ25lJTIwY2hyaXN0bWFzJTIwbWFya2V0fGVufDB8MHx8fDE3OTA1MjA2ODJ8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Carmela", link: "https://unsplash.com/photos/a-group-of-people-standing-in-front-of-a-building-KPt2zBkx5aY" },
    KRK: { url: "https://images.unsplash.com/photo-1575659458448-27b1d2836de2?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxLcmFrb3clMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4NHww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Daniels Joffe", link: "https://unsplash.com/photos/lit-village-pkDKjsPAAi4" },
    TLL: { url: "https://images.unsplash.com/photo-1638825183364-01e8b64b00e0?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxUYWxsaW5uJTIwY2hyaXN0bWFzJTIwbWFya2V0fGVufDB8MHx8fDE3OTA1MjA2ODV8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Dmitry Sumin", link: "https://unsplash.com/photos/an-aerial-view-of-a-snowy-city-at-night-6t91NtWXlco" },
    BRU: { url: "https://images.unsplash.com/photo-1642834502042-a77e97a696b9?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxCcnVzc2VscyUyMGNocmlzdG1hc3xlbnwwfDB8fHwxNzkwNTIwNjg0fDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Paolo Margari", link: "https://unsplash.com/photos/a-group-of-people-standing-in-front-of-a-tall-building-zKbuYNG5iBk" },
    CPH: { url: "https://images.unsplash.com/photo-1604947105796-22799ff21167?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxDb3BlbmhhZ2VuJTIwY2hyaXN0bWFzfGVufDB8MHx8fDE3OTA1MjA2ODR8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Razvan Mirel", link: "https://unsplash.com/photos/white-boat-on-dock-near-buildings-during-night-time-j1kZcmq3oRc" },
    BSL: { url: "https://images.unsplash.com/photo-1735059744740-e23efa9ffb48?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxCYXNlbCUyMGNocmlzdG1hc3xlbnwwfDB8fHwxNzkwNTIwNjg0fDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Ryan Lee", link: "https://unsplash.com/photos/a-room-filled-with-lots-of-christmas-trees-utWlCtOb4pQ" },
    EDI: { url: "https://images.unsplash.com/photo-1546617605-31567bc8c7d3?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxFZGluYnVyZ2glMjBjaHJpc3RtYXN8ZW58MHwwfHx8MTc5MDUyMDY4NXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Roan Lavery", link: "https://unsplash.com/photos/aerial-view-photography-of-city-at-night-U4fAZiF_S2A" },
    RVN: { url: "https://images.unsplash.com/photo-1736271148258-1a7668d0646c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwzfHxSb3ZhbmllbWklMjBsYXBsYW5kJTIwd2ludGVyfGVufDB8MHx8fDE3OTA1MjA2ODZ8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Dylan Shaw", link: "https://unsplash.com/photos/a-person-walking-through-a-snow-covered-field-W0bOCi6h6X8" },
    TOS: { url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxUcm9tc28lMjBub3J0aGVybiUyMGxpZ2h0c3xlbnwwfDB8fHwxNzkwNTIwNjg2fDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Lightscape", link: "https://unsplash.com/photos/northern-lights-over-snow-capped-mountian-LtnPejWDSAY" },
    INN: { url: "https://images.unsplash.com/photo-1553537316-86354ef82879?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxJbm5zYnJ1Y2slMjBzbm93fGVufDB8MHx8fDE3OTA1MjA2ODR8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Anna Rosar", link: "https://unsplash.com/photos/view-of-buildings-2V0EXtFqdJQ" },
    NYC: { url: "https://images.unsplash.com/photo-1672391509386-a73ada294e32?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxOZXclMjBZb3JrJTIwY2hyaXN0bWFzfGVufDB8MHx8fDE3OTA1MjA2ODV8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Kaydn Ito", link: "https://unsplash.com/photos/a-large-christmas-tree-in-a-city-square-ev0lnT_qseg" },
    LON: { url: "https://images.unsplash.com/photo-1514729797186-944d57303199?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxMb25kb24lMjBjaHJpc3RtYXMlMjBsaWdodHN8ZW58MHwwfHx8MTc5MDUyMDY4NXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Jamie Davies", link: "https://unsplash.com/photos/photo-of-bus-passing-on-city-with-lights-7iNteV_zTRU" },
    PAR: { url: "https://images.unsplash.com/photo-1641503855609-5e28a1ed35a9?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxQYXJpcyUyMGNocmlzdG1hc3xlbnwwfDB8fHwxNzkwNTIwNjg1fDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Pierre Blaché", link: "https://unsplash.com/photos/a-city-street-filled-with-lots-of-traffic-at-night-sgTCFeEiVow" },
    AMS: { url: "https://images.unsplash.com/photo-1672826708086-b81f36475519?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxBbXN0ZXJkYW0lMjBjaHJpc3RtYXN8ZW58MHwwfHx8MTc5MDUyMDY4NXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Artem Shuba", link: "https://unsplash.com/photos/a-lighted-christmas-tree-on-a-bridge-over-a-river-I6I_cbOn_rc" },
    BER: { url: "https://images.unsplash.com/photo-1639333480194-8bda670e4633?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwyfHxCZXJsaW4lMjBjaHJpc3RtYXMlMjBtYXJrZXR8ZW58MHwwfHx8MTc5MDUyMDY4NHww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Babak Habibi", link: "https://unsplash.com/photos/a-group-of-people-standing-in-front-of-a-building-AbaZvPHuHMk" },
    TFS: { url: "https://images.unsplash.com/photo-1740429960646-eafd96293397?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwzfHxUZW5lcmlmZSUyMGJlYWNofGVufDB8MHx8fDE3OTA1MjA2ODZ8MA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Luis Gonçalves", link: "https://unsplash.com/photos/an-aerial-view-of-a-beach-with-a-boat-in-the-water-xPmVUd9NBrQ" },
    FNC: { url: "https://images.unsplash.com/photo-1674333362725-84e9996aa6fb?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwxfHxNYWRlaXJhJTIwRnVuY2hhbHxlbnwwfDB8fHwxNzkwNTIwNjg1fDA&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Sofia Vila Flor", link: "https://unsplash.com/photos/a-scenic-view-of-a-city-and-a-body-of-water-I3GXE-zNcBA" },
    DXB: { url: "https://images.unsplash.com/photo-1607414851776-f2fcc379fb48?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&ixid=M3w4NDUzMDJ8MHwxfHNlYXJjaHwzfHxEdWJhaSUyMHNreWxpbmV8ZW58MHwwfHx8MTc5MDUyMDY4NXww&ixlib=rb-4.1.0\&q=70\&w=500&auto=format%2Ccompress", photographer: "Karen Dalton", link: "https://unsplash.com/photos/city-skyline-across-body-of-water-during-sunset-nk7rQ24o0v8" },
};
